version: 2

jobs:
  build:
    docker:
      - image: "nvidia/cuda:11.0-devel-ubuntu18.04"
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      LANGUAGE: C.UTF-8
    steps:
      - checkout
      - run:
          name: Installing Packages
          command: |
           apt-get update
           apt-get install -y sudo gcc g++ cmake git
           rm -rf /var/lib/apt/lists/*
      - run:
          name: Init Submodules
          command: |
            git submodule init
            git submodule update
      - run:
          name: Build
          command: 'bash ./scripts/build.sh'
      - run:
          name: Run Unit Tests
          command: 'bash ./scripts/test.sh'
#      - run:
#          name: Install Python
#          command: 'apt-get update
#          && sudo apt-get install -y python3.6
#          && sudo apt-get install -y python3-pip
#          && pip3 install --upgrade pip'
#      - run:
#          name: Install Python Packages
#          command: |
#            sudo pip install pipenv
#            pipenv install
#      - run:
#          name: Run Custom Tests
#          command: pipenv run python ./custom-tests/test-custom-cases.py