#ifndef ICCAD2020_CONSTANTS_H
#define ICCAD2020_CONSTANTS_H

using CAPACITY_TYPE = unsigned short int;
using NUM_ARG_TYPE = uint8_t;

const unsigned int N_CELL_PARALLEL = 512;
const unsigned int N_STIMULI_PARALLEL = 256;
const CAPACITY_TYPE INITIAL_CAPACITY = 16;
const NUM_ARG_TYPE MAX_NUM_MODULE_OUTPUT = 10;
const NUM_ARG_TYPE MAX_NUM_MODULE_ARGS = 20;

#endif
