#ifndef ICCAD2020_CONSTANTS_H
#define ICCAD2020_CONSTANTS_H

using CAPACITY_TYPE = unsigned int;
using NUM_ARG_TYPE = unsigned char;

const unsigned int N_STREAM = 16;
const unsigned int N_SIM_RESULT_THREAD = 32;
const unsigned int N_CELL_PARALLEL = 256;
const unsigned int N_STIMULI_PARALLEL = 32;
const CAPACITY_TYPE INITIAL_CAPACITY = 16;
const NUM_ARG_TYPE MAX_NUM_MODULE_INPUT = 6;
const NUM_ARG_TYPE MAX_NUM_MODULE_OUTPUT = 3;
const NUM_ARG_TYPE MAX_NUM_MODULE_ARGS = MAX_NUM_MODULE_INPUT + MAX_NUM_MODULE_OUTPUT;

const auto CAPACITY_UPPER_BOUND = INITIAL_CAPACITY * MAX_NUM_MODULE_INPUT;
#endif
